### PR TITLE
Check before use fix

### PR DESCRIPTION
**Pull request by cheplv**
Prev commit fix - there was problem with menu tree generation

### CODE REVIEW

**Comment by cheplv** [comment]
@GasimGasimzada can you accept this PR?

**Comment by GasimGasimzada** [comment]
Done

**Comment by cheplv** [comment]
@GasimGasimzada seems need to create new release

**Comment by cheplv** [comment]
@GasimGasimzada may be need to merge other pull requests from original qtranslate-x - because it was updated 2 years ago?

**Comment by GasimGasimzada** [comment]
what do you mean? I will create a new release.

**Comment by cheplv** [comment]
@GasimGasimzada yes - need new release ASAP :)

**Comment by cheplv** [comment]
@GasimGasimzada update via composer gives still old version without this fix

**Pull request merged**
